# Se eliminó la línea "version" obsoleta

networks:
  saga-network:
    driver: bridge

services:
  saga-bus:
    image: jrgiadach/soabus:latest
    container_name: saga-bus-container
    ports:
      - "5001:5000"
    networks:
      - saga-network
    restart: unless-stopped

  saga-chromadb:
    image: chromadb/chroma:latest
    container_name: saga-chroma-container
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - saga-network
    restart: unless-stopped

  servicio-metricas:
    build:
      context: .
      dockerfile: services/metri/Dockerfile
    container_name: saga-servicio-metricas
    networks:
      - saga-network
    environment:
      - BUS_HOST=saga-bus-container 
      - BUS_PORT=5000
    depends_on:
      - saga-bus
    restart: unless-stopped

  agente-monitor:
    build:
      context: .
      dockerfile: clients/monitor_agente/Dockerfile
    container_name: saga-agente-monitor
    networks:
      - saga-network
    environment:
      - BUS_HOST=saga-bus-container
      - BUS_PORT=5000
    depends_on:
      - saga-bus
    restart: unless-stopped