global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'saga-ragsv'
    static_configs:
      - targets: ['saga-service-ragsv:8001']

  - job_name: 'saga-monitor-agente'
    static_configs:
      - targets: ['host.docker.internal:8002']
